"""Small, offline theme renderers using the shell's semantic palette."""
import plistlib
import re
import shlex

NAME = 'quickshell-config'
TMUX_ROLES = ('bg', 'surface', 'overlay', 'muted', 'subtle', 'text', 'love', 'gold',
              'rose', 'pine', 'foam', 'iris', 'highlightLow', 'highlightMed', 'highlightHigh',
              'on_iris', 'on_rose', 'on_pine')
ROLES = ('bg', 'surface', 'overlay', 'muted', 'subtle', 'text', 'love', 'gold',
         'rose', 'pine', 'foam', 'iris', 'highlightLow', 'highlightMed', 'highlightHigh')


def validate(palette, mode):
    if mode not in ('dark', 'light') or not isinstance(palette, dict):
        raise ValueError('Invalid theme mode or palette')
    if any(not isinstance(palette.get(k), str) or not re.fullmatch(r'#[0-9a-fA-F]{6}', palette[k]) for k in ROLES):
        raise ValueError('The palette must contain all shell colors as #RRGGBB')
    return {k: palette[k].lower() for k in ROLES}


def rgb(color):
    return tuple(int(color[i:i + 2], 16) for i in (1, 3, 5))


def mix(a, b, amount):
    return '#' + ''.join(f'{round(x * (1 - amount) + y * amount):02x}' for x, y in zip(rgb(a), rgb(b)))


def on_color(background):
    # Black or white, whichever has better WCAG contrast with the accent.
    channels = [v / 255 for v in rgb(background)]
    linear = [v / 12.92 if v <= .04045 else ((v + .055) / 1.055) ** 2.4 for v in channels]
    luminance = sum(a * b for a, b in zip(linear, (.2126, .7152, .0722)))
    return '#000000' if luminance > .179 else '#ffffff'


def hyprland_colors(p, lua=False):
    if lua:
        return f'''-- Generated by Quickshell; disable Hyprland colors to restore your colors.
hl.config({{
    general = {{ col = {{
        active_border = {{ colors = {{ "rgb({p['iris'][1:]})", "rgb({p['rose'][1:]})" }}, angle = 45 }},
        inactive_border = "rgb({p['highlightMed'][1:]})",
    }} }},
}})
'''
    return f'''# Generated by Quickshell; disable Hyprland colors to restore your colors.
general {{
    col.active_border = rgb({p['iris'][1:]}) rgb({p['rose'][1:]}) 45deg
    col.inactive_border = rgb({p['highlightMed'][1:]})
}}
'''


def hyprland(p, lua=False, appearance=None):
    """Appearance only: leave input, monitors, workspaces and bindings alone."""
    defaults = dict(radius=0, opacity=1, verticalGap=0, horizontalGap=0, innerGap=8, borderWidth=1)
    if appearance is None:
        appearance = defaults
    if not isinstance(appearance, dict):
        raise ValueError('Invalid Hyprland appearance settings.')
    values = dict(defaults, **appearance)
    for key, maximum in [('radius', 100), ('verticalGap', 40), ('horizontalGap', 40), ('innerGap', 100), ('borderWidth', 10)]:
        if type(values[key]) is not int or not 0 <= values[key] <= maximum:
            raise ValueError('Invalid Hyprland appearance: ' + key)
    if type(values['opacity']) not in (int, float) or not 0.2 <= values['opacity'] <= 1:
        raise ValueError('Invalid Hyprland appearance: opacity')
    radius, opacity = values['radius'], values['opacity']
    vertical, horizontal = values['verticalGap'], values['horizontalGap']
    gap, border = values['innerGap'], values['borderWidth']
    if lua:
        return f'''-- Generated by Quickshell; disable Hyprland appearance to restore your styling.
hl.config({{
    general = {{
        gaps_in = {gap}, gaps_out = {{ top = {vertical}, bottom = {vertical}, left = {horizontal}, right = {horizontal} }}, border_size = {border},
    }},
    decoration = {{
        rounding = {radius}, rounding_power = 2,
        active_opacity = {opacity}, inactive_opacity = {opacity},
        blur = {{ enabled = true, size = 5, passes = 2, noise = 0.02, contrast = 1.0, brightness = 1.0, vibrancy = 0.2 }},
    }},
}})
'''
    return f'''# Generated by Quickshell; disable Hyprland appearance to restore your styling.
general {{
    gaps_in = {gap}
    gaps_out = {vertical}, {horizontal}, {vertical}, {horizontal}
    border_size = {border}
}}
decoration {{
    rounding = {radius}
    rounding_power = 2
    active_opacity = {opacity}
    inactive_opacity = {opacity}
    blur {{
        enabled = true
        size = 5
        passes = 2
        noise = 0.02
        contrast = 1.0
        brightness = 1.0
        vibrancy = 0.2
    }}
}}
'''


def hyprlock_path(value):
    if any(c in value for c in '\r\n\x00$#{}') or value != value.strip():
        raise ValueError('Hyprlock paths cannot contain newlines, $, #, braces, or leading/trailing whitespace. Rename the file or folder.')
    return value


def hyprlock(p, background, image, helper):
    command = 'python3 ' + shlex.quote(hyprlock_path(helper))
    colors = {key: f'rgb({value[1:]})' for key, value in p.items()}
    return f'''# Generated by Quickshell. Disable Hyprlock sync to restore the previous config.
general {{
    hide_cursor = true
}}

background {{
    monitor =
    path = {hyprlock_path(image)}
    color = rgb({background[1:]})
    blur_passes = 0
}}

# Opaque panel keeps the clock and warnings readable over any picture/color.
shape {{
    monitor =
    size = 480, 420
    color = {colors['bg']}
    rounding = 24
    position = 0, 40
    halign = center
    valign = center
    zindex = 0
}}

label {{
    monitor =
    text = $TIME
    color = {colors['text']}
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
    zindex = 1
}}

input-field {{
    monitor =
    size = 320, 60
    outline_thickness = 2
    outer_color = {colors['iris']}
    inner_color = {colors['surface']}
    font_color = {colors['text']}
    font_family = JetBrainsMono Nerd Font
    check_color = {colors['foam']}
    fail_color = {colors['love']}
    capslock_color = {colors['gold']}
    bothlock_color = {colors['gold']}
    fade_on_empty = false
    placeholder_text = Password
    rounding = 10
    position = 0, 30
    halign = center
    valign = center
    zindex = 1
}}

label {{
    monitor =
    text = Keyboard layout: $LAYOUT
    color = {colors['gold']}
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -40
    halign = center
    valign = center
    zindex = 1
}}

label {{
    monitor =
    text = cmd[update:500] {command}
    color = {colors['gold']}
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, -80
    halign = center
    valign = center
    zindex = 1
}}
'''


def tmux(p):
    values = dict(p, **{'on_' + role: on_color(p[role]) for role in ('iris', 'rose', 'pine')})
    return '# Generated by Quickshell. Colors only; layout stays in tmux/theme.conf.\n' + ''.join(
        f'set-option -g @quickshell_{role} "{values[role]}"\n' for role in TMUX_ROLES)


def rofi(p):
    # Color overrides only: keep the user's font, dimensions and widget layout.
    values = dict(background=p['bg'], foreground=p['text'],
                  background_color=p['bg'], text_color=p['text'],
                  bordercolor=p['highlightMed'], separatorcolor=p['highlightMed'])
    # Also update the short color names used by the dotfiles' existing theme.
    values.update({key: p[role] for key, role in dict(bg='bg', cur='overlay', fgd='text',
                   cmt='muted', cya='foam', grn='pine', ora='rose', pur='iris', red='love', yel='gold').items()})
    states = {'normal': (p['bg'], p['text']), 'active': (p['surface'], p['foam']),
              'urgent': (p['love'], on_color(p['love']))}
    rules = []
    for variant in ('normal', 'alternate', 'selected'):
        for state, (bg, fg) in states.items():
            if variant == 'selected':
                bg = p['love'] if state == 'urgent' else p['iris']
                fg = on_color(bg)
            elif variant == 'alternate' and state == 'normal':
                bg = p['surface']
            values[f'{variant}-{state}-background'] = bg
            values[f'{variant}-{state}-foreground'] = fg
            rules.append(f'element {variant}.{state} {{ background-color: {bg}; text-color: {fg}; }}\n')
    for state, (bg, fg) in states.items():
        values[state + '-background'] = bg
        values[state + '-foreground'] = fg
    values['selected-background'] = p['iris']
    result = '/* Generated by Quickshell. Colors only. */\n* {\n' + ''.join(
        f'    {key.replace("_", "-")}: {value};\n' for key, value in values.items()) + '}\n'
    result += f'''window, mainbox, listview {{ background-color: {p['bg']}; }}
window, listview, message, sidebar {{ border-color: {p['highlightMed']}; }}
inputbar, message {{ background-color: {p['surface']}; text-color: {p['text']}; }}
textbox, button, case-indicator {{ background-color: transparent; text-color: {p['text']}; }}
entry {{ background-color: transparent; text-color: {p['text']}; placeholder-color: {p['muted']}; }}
prompt, textbox-prompt-colon {{ background-color: transparent; text-color: {p['iris']}; }}
num-filtered-rows, num-rows, textbox-num-sep {{ background-color: transparent; text-color: {p['subtle']}; }}
scrollbar {{ background-color: {p['surface']}; handle-color: {p['highlightHigh']}; }}
button selected {{ background-color: {p['iris']}; text-color: {on_color(p['iris'])}; }}
element-text, element-icon {{ background-color: inherit; text-color: inherit; }}
element-text {{ highlight: bold underline; }}
'''
    return result + ''.join(rules)


def ansi(p):
    normal = [p['bg'], p['love'], mix(p['foam'], p['gold'], .25), p['gold'],
              p['pine'], p['iris'], p['foam'], p['text']]
    return normal + [p['muted']] + [mix(c, p['text'], .25) for c in normal[1:7]] + [p['text']]


def gtk(p):
    colors = dict(accent_color=p['iris'], accent_bg_color=p['iris'], accent_fg_color=on_color(p['iris']),
                  destructive_color=p['love'], destructive_bg_color=p['love'], destructive_fg_color=on_color(p['love']),
                  success_color=p['foam'], warning_color=p['gold'], error_color=p['love'],
                  theme_bg_color=p['bg'], theme_fg_color=p['text'], theme_base_color=p['surface'],
                  theme_text_color=p['text'], theme_selected_bg_color=p['iris'], theme_selected_fg_color=on_color(p['iris']),
                  insensitive_bg_color=p['surface'], insensitive_fg_color=p['muted'], borders=p['highlightMed'],
                  theme_unfocused_bg_color=p['bg'], theme_unfocused_fg_color=p['subtle'],
                  theme_unfocused_base_color=p['surface'], theme_unfocused_text_color=p['text'],
                  theme_unfocused_selected_bg_color=p['highlightHigh'], theme_unfocused_selected_fg_color=p['text'])
    for name, bg in [('window', 'bg'), ('view', 'surface'), ('headerbar', 'surface'),
                     ('popover', 'overlay'), ('dialog', 'overlay'), ('card', 'surface'),
                     ('sidebar', 'surface'), ('secondary_sidebar', 'overlay'), ('thumbnail', 'surface')]:
        colors[name + '_bg_color'] = p[bg]
        colors[name + '_fg_color'] = p['text']
    colors['headerbar_backdrop_color'] = p['bg']
    colors['headerbar_border_color'] = p['highlightMed']
    legacy = '/* Generated by Quickshell. */\n' + ''.join(f'@define-color {k} {v};\n' for k, v in colors.items())
    # GTK 4/libadwaita supports both named colors and modern CSS variables.
    modern = legacy + ':root {\n' + ''.join(f'  --{k.replace("_", "-")}: {v};\n' for k, v in colors.items()
                                          if not k.startswith(('theme_', 'insensitive_'))) + '}\n'
    return legacy, modern


def terminal(p, target):
    colors = ansi(p)
    if target == 'ghostty':
        return ''.join(f'palette = {i}={c}\n' for i, c in enumerate(colors)) + ''.join(
            f'{k} = {v}\n' for k, v in {'background': p['bg'], 'foreground': p['text'],
            'cursor-color': p['iris'], 'cursor-text': on_color(p['iris']),
            'selection-background': p['highlightHigh'], 'selection-foreground': p['text']}.items())
    colors_body = ''.join(f'{k}={v[1:]}\n' for k, v in {
        'background': p['bg'], 'foreground': p['text'], 'selection-background': p['highlightHigh'],
        'selection-foreground': p['text']}.items()) + ''.join(
        f'{"regular" if i < 8 else "bright"}{i % 8}={c[1:]}\n' for i, c in enumerate(colors))
    return '[colors-dark]\n' + colors_body + '\n[colors-light]\n' + colors_body


def kde(p):
    result = {'General': {'ColorScheme': NAME, 'Name': 'Quickshell'}, 'KDE': {'contrast': '4'}}
    for group, bg in [('Window', 'bg'), ('View', 'surface'), ('Button', 'overlay'), ('Selection', 'iris'),
                      ('Tooltip', 'overlay'), ('Complementary', 'surface'), ('Header', 'surface')]:
        selected = group == 'Selection'
        values = {'BackgroundNormal': p[bg], 'BackgroundAlternate': p['overlay'],
                  'ForegroundNormal': on_color(p['iris']) if selected else p['text'],
                  'ForegroundInactive': p['subtle'], 'ForegroundActive': p['iris'],
                  'ForegroundLink': p['pine'], 'ForegroundVisited': p['rose'],
                  'ForegroundNegative': p['love'], 'ForegroundNeutral': p['gold'],
                  'ForegroundPositive': p['foam'], 'DecorationFocus': p['iris'], 'DecorationHover': p['foam']}
        result['Colors:' + group] = {k: ','.join(map(str, rgb(v))) for k, v in values.items()}
    return result


def ini(sections):
    return ''.join(f'[{section}]\n' + ''.join(f'{k}={v}\n' for k, v in values.items()) + '\n'
                   for section, values in sections.items())


def qt(p):
    values = [p['text'], p['overlay'], p['highlightHigh'], p['highlightMed'], p['bg'], p['muted'],
              p['text'], p['text'], p['text'], p['surface'], p['bg'], p['bg'], p['iris'], on_color(p['iris']),
              p['pine'], p['rose'], p['overlay'], p['surface'], p['overlay'], p['text'], p['subtle'], p['iris']]
    disabled = values[:]
    for i in (0, 6, 8, 19):
        disabled[i] = p['muted']
    return ini({'ColorScheme': {'active_colors': ', '.join(values), 'inactive_colors': ', '.join(values),
                                 'disabled_colors': ', '.join(disabled)}})


def btop(p):
    values = dict(main_bg=p['bg'], main_fg=p['text'], title=p['iris'], hi_fg=p['foam'],
                  selected_bg=p['highlightMed'], selected_fg=p['text'], inactive_fg=p['muted'],
                  graph_text=p['subtle'], meter_bg=p['highlightLow'], proc_misc=p['rose'], div_line=p['highlightMed'])
    for group in ('cpu', 'mem', 'net', 'proc'):
        values[group + '_box'] = p['iris']
    for group in ('temp', 'cpu', 'free', 'cached', 'available', 'used', 'download', 'upload'):
        for stage, role in [('start', 'pine'), ('mid', 'foam'), ('end', 'love' if group == 'temp' else 'iris')]:
            values[group + '_' + stage] = p[role]
    return ''.join(f'theme[{k}]="{v}"\n' for k, v in values.items())


def yazi(p):
    def style(fg, bg=None):
        return '{ fg = "' + fg + '"' + (', bg = "' + bg + '"' if bg else '') + ' }'
    sections = {'mgr': {'cwd': style(p['foam']), 'border_style': style(p['highlightHigh']),
                       'find_keyword': style(p['love']), 'marker_selected': style(p['iris'])},
                'tabs': {'active': style(on_color(p['iris']), p['iris']), 'inactive': style(p['subtle'], p['surface'])},
                'status': {'overall': style(p['text'], p['surface']), 'progress_normal': style(p['foam'], p['overlay']),
                           'progress_error': style(p['love'], p['overlay'])},
                'mode': {}, 'input': {'border': style(p['iris']), 'value': style(p['text'])},
                'pick': {'border': style(p['iris']), 'active': style(p['iris'])},
                'which': {'mask': style(p['text'], p['bg']), 'cand': style(p['foam']), 'desc': style(p['text'])},
                'confirm': {'border': style(p['iris']), 'title': style(p['text'])}}
    for mode, role in [('normal', 'iris'), ('select', 'foam'), ('unset', 'rose')]:
        sections['mode'][mode + '_main'] = style(on_color(p[role]), p[role])
        sections['mode'][mode + '_alt'] = style(p['text'], p['overlay'])
    flavor = ini(sections)
    syntax = {'name': 'Quickshell', 'settings': [{'settings': {'background': p['bg'], 'foreground': p['text']}}]}
    for scope, role in [('comment', 'muted'), ('string', 'foam'), ('keyword', 'iris'), ('constant', 'gold'),
                        ('entity.name.function', 'pine'), ('entity.name.type', 'rose'), ('invalid', 'love')]:
        syntax['settings'].append({'scope': scope, 'settings': {'foreground': p[role]}})
    return flavor, plistlib.dumps(syntax).decode()


def spotify(p):
    roles = {'text': 'text', 'subtext': 'subtle', 'main': 'bg', 'sidebar': 'surface', 'player': 'surface',
             'card': 'overlay', 'shadow': 'bg', 'selected-row': 'highlightHigh', 'button': 'iris',
             'button-active': 'foam', 'button-disabled': 'muted', 'tab-active': 'overlay',
             'notification': 'pine', 'notification-error': 'love', 'misc': 'highlightMed', 'highlight': 'overlay'}
    return ini({'Base': {k: p[v][1:] for k, v in roles.items()}})


def discord(p):
    values = {'background-primary': 'bg', 'background-secondary': 'surface', 'background-tertiary': 'overlay',
              'background-floating': 'overlay', 'background-base-lowest': 'bg', 'background-base-lower': 'surface',
              'background-base-low': 'overlay', 'background-surface-high': 'overlay',
              'background-surface-higher': 'surface', 'background-surface-highest': 'overlay',
              'text-normal': 'text', 'text-default': 'text', 'text-muted': 'subtle', 'header-primary': 'text',
              'header-secondary': 'subtle', 'interactive-normal': 'subtle', 'interactive-hover': 'text',
              'interactive-active': 'text', 'interactive-muted': 'muted', 'brand-500': 'iris',
              'brand-experiment': 'iris', 'text-link': 'pine', 'status-danger': 'love', 'status-positive': 'foam',
              'background-modifier-selected': 'highlightMed', 'channeltextarea-background': 'overlay'}
    return '/**\n * @name Quickshell\n * @description Colors from the Quickshell bar\n * @author Quickshell config\n * @version 1.0.0\n */\n' + \
        ':root, .theme-dark, .theme-light {\n' + ''.join(f'  --{k}: {p[v]} !important;\n' for k, v in values.items()) + '}\n'


def zen(p, mode):
    """Browser chrome only: leave websites, extensions and workspace data alone."""
    values = {
        'zen-primary-color': 'iris', 'zen-colors-primary': 'bg',
        'zen-colors-secondary': 'surface', 'zen-colors-tertiary': 'bg',
        'zen-colors-primary-foreground': 'text', 'zen-colors-border': 'highlightMed',
        'zen-colors-border-contrast': 'highlightHigh', 'zen-colors-hover-bg': 'overlay',
        'zen-colors-input-bg': 'surface', 'zen-input-border-color': 'highlightMed',
        'zen-main-browser-background': 'bg', 'zen-main-browser-background-toolbar': 'bg',
        'zen-themed-toolbar-bg': 'bg', 'zen-themed-toolbar-bg-transparent': 'bg',
        'zen-toolbar-element-bg': 'surface', 'zen-toolbar-element-bg-hover': 'overlay',
        'zen-urlbar-background': 'surface', 'zen-dialog-background': 'overlay',
        'toolbar-bgcolor': 'bg', 'toolbar-background-color': 'bg',
        'toolbox-bgcolor-inactive': 'bg', 'toolbar-color': 'text',
        'toolbox-textcolor': 'text', 'toolbox-textcolor-inactive': 'subtle',
        'lwt-text-color': 'text', 'toolbar-field-background-color': 'surface',
        'toolbar-field-color': 'text', 'toolbar-field-focus-color': 'text',
        'toolbar-field-focus-background-color': 'overlay', 'toolbar-field-focus-border-color': 'iris',
        'toolbarbutton-icon-fill': 'text', 'toolbarbutton-icon-fill-attention': 'iris',
        'toolbarbutton-background-color-hover': 'overlay', 'toolbarbutton-background-color-active': 'highlightMed',
        'tab-selected-bgcolor': 'overlay', 'tab-selected-textcolor': 'text',
        'tab-hover-background-color': 'surface', 'tab-loading-fill': 'iris',
        'arrowpanel-background': 'overlay', 'arrowpanel-color': 'text',
        'arrowpanel-border-color': 'highlightMed', 'panel-separator-color': 'highlightMed',
        'sidebar-background-color': 'bg', 'sidebar-text-color': 'text',
        'lwt-sidebar-background-color': 'bg', 'lwt-sidebar-text-color': 'text',
        'input-background-color': 'surface', 'input-color': 'text',
        'input-border-color': 'highlightMed', 'focus-outline-color': 'iris',
        'button-background-color-primary': 'iris', 'button-primary-hover-bgcolor': 'foam',
        'button-primary-active-bgcolor': 'pine', 'color-accent-primary': 'iris',
        'in-content-primary-button-background': 'iris', 'in-content-primary-button-background-hover': 'foam',
    }
    return ('/* Generated by Quickshell. Browser UI only. */\n:root {\n'
            + f'  color-scheme: {mode} !important;\n'
            + ''.join(f'  --{key}: {p[role]} !important;\n' for key, role in values.items())
            + f'  --button-primary-color: {on_color(p["iris"])} !important;\n'
            + f'  --in-content-primary-button-text-color: {on_color(p["iris"])} !important;\n'
            + '}\n#navigator-toolbox, #zen-appcontent-navbar-container {\n'
            + f'  background: {p["bg"]} !important;\n  color: {p["text"]} !important;\n'
            + '}\n#urlbar-background {\n'
            + f'  background: {p["surface"]} !important;\n'
            + '}\n')
